//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::investigations::Entity as Investigations;
pub use super::users::Entity as Users;
pub use super::users_investigations::Entity as UsersInvestigations;
