//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users_investigations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_uuid: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub investigation_uuid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::investigations::Entity",
        from = "Column::InvestigationUuid",
        to = "super::investigations::Column::Uuid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Investigations,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserUuid",
        to = "super::users::Column::Uuid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::investigations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Investigations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
